# Generated by Django 3.0.5 on 2020-06-24 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillup',
            name='gallons',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fillup',
            name='price_per_gallon',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fillup',
            name='trip_distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
