# Generated by Django 3.0.5 on 2020-06-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillups', '0002_auto_20200608_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
